import logo from '../images/logo/logo.png'
import crossintersection from '../images/crossintersection/crossintersection.png'
import drawericon from '../images/drawericon/drawericon.png'
import headerintersection from '../images/headerintersection/headerintersection.png'
import backarrow from '../images/backarrow/backarrow.png'
import search from '../images/search/search.png'
import month from '../images/month/month.png'
import allprograms from '../images/allprograms/allprograms.png'
import news from '../images/news/news.png'
import media from '../images/media/media.png'
import appicon from '../images/appicon/appicon.png'
import upArrow from '../images/upArrow/upArrow.png'
import downArrow from '../images/downArrow/downArrow.png'
import drawerlogo from '../images/drawerlogo/drawerlogo.png'
import arabic from '../images/arabic/arabic.png'
import programs from '../images/programs/programs.png'

import nextarrow from '../images/nextarrow/nextarrow.png'
import diploma from '../images/diploma/diploma.png'
import certificates from '../images/certificates/certificates.png'
import higherstudy from '../images/higherstudy/higherstudy.png'
import arrowintersection from '../images/arrowintersection/arrowintersection.png'
import bookshelf from '../images/bookshelf/bookshelf.png'
import dotintersection from '../images/dotintersection/dotintersection.png'
import olympics from '../images/olympics/olympics.png'
import hands from '../images/hands/hands.png'
import translation from '../images/translation/translation.png'
import filter from '../images/filter/filter.png'

export { logo, crossintersection, drawericon, headerintersection, backarrow, search, month, allprograms, news, media, appicon, upArrow, downArrow, drawerlogo, arabic, programs, diploma, nextarrow, certificates, higherstudy, arrowintersection, bookshelf, dotintersection, olympics, hands, translation, filter }